version: 0.0
os: linux
files:
  - source: GrailsSample/target/GrailsSample.war
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: GrailsSample/scripts/stop_application
      timeout: 300
