version: 0.0
os: linux
files:
  - source: /target/GrailsSample.war
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: scripts/stop_application
      timeout: 300
